name=input("what is your name?")
age=input("what is your age?")
university=input("what is your university?")
department=input("what is your department?")
print("Hello ", name)
print("welcome to ", university)
print("you are studying ", department)
print("you are ", age, "years old")
print("have a wonderful day!")
