food=input("what is your favourite food?")
club=input("what is your favourite football club?")
movie=input("what is your favourite movie?")
friend=input("who is your best friend?")
girlfriend=input("who is your girlfriend?")
name=input("what is your name?")
print("hello", name)
print(girlfriend, "is your girl")
print("you are a fan of", club)
print("your favourite food is", food)
print(movie, "is your favourite movie")
print("your best friend is", friend)
print("here are some informations about you. have a good day!")
